apiVersion: v1
kind: ServiceAccount
metadata:
  name: dt-consumer
  namespace: consumer
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.email }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt-consumer
  namespace: consumer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dt-consumer
  template:
    metadata:
      labels:
        app: dt-consumer
    spec:
      serviceAccountName: dt-consumer
      containers:
        - name: dt-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROJECT_ID
              value: {{ .Values.projectId }}
---
apiVersion: v1
kind: Service
metadata:
  name: dt-consumer
  namespace: consumer
spec:
  selector:
    app: dt-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dt-consumer-hpa
  namespace: consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dt-consumer
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: External
    external:
      metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.subscription_id: dt-message-subscription
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.targetAverageValue }}